spring.application.name=airline-booking
server.port=${SERVER_PORT:8082}

#MYSQL CONNECTION
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Use 'update' only during development
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}

jwtSecretString=${JWT_SECRET}

# Mail configuration
# username is your email, password is your app password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

frontendLoginUrl=${FRONTEND_LOGIN_URL}
viewBookingUrl=${VIEW_BOOKING_URL}

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

server.forward-headers-strategy=framework